package com.example.utsmobile;

import java.util.ArrayList;

public class DataSource {

    public static ArrayList<Stories> stories = StoriesData();

    public static ArrayList<Stories> StoriesData(){
        ArrayList<Stories> stories = new ArrayList<>();
        stories.add(new Stories("The Frog-King, or Iron Henry",
                "   In olden times when wishing still helped one, there lived a king whose daughters" +
                " were all beautiful, but the youngest was so beautiful that the sun itself, which has seen so much, was astonished whenever it shone in her face. " +
                "Close by the King’s castle lay a great dark forest, and under an old lime-tree in the forest was a well, " +
                "and when the day was very warm, the King’s child went out into the forest and sat down by the side of the cool fountain; " +
                "and when she was bored she took a golden ball, and threw it up on high and caught it; and this ball was her favorite plaything.\n" +"\n"+
                "   Now it so happened that on one occasion the princess’s golden ball did not fallinto the little hand which she was holding up for it, but on to the ground beyond," +
                "and rolled straight into the water. The King’s daughter followed it with her eyes, but it vanished, and the well was deep, so deep that the bottom could not be seen. " +
                "At this she began to cry, and cried louder and louder, and could not be comforted. And as she thus lamented, someone said to her: “What ails you, King’s daughter? " +
                "You weep so that even a stone would show pity.” She looked round to the side from whence the voice came, and saw a frog stretching forth its big, ugly head from the water. " +
                "“Ah! old water-splasher, is it you?” said she; “I am weeping for my golden ball, which has fallen into the well.”\n" + "\n"+
                "   “Be quiet, and do not weep,” answered the frog, “I can help you, but what will you give me if I bring your plaything up again?”\n" +
                "   “Whatever you will have, dear frog,” said she—“my clothes, my pearls and jewels, and even the golden crown which I am wearing.”\n" +
                "   The frog answered: “I do not care for your clothes, your pearls and jewels, nor for your golden crown; but if you will love me and let me be your companion" +
                "and play-fellow, and sit by you at your little table, and eat off your little golden plate, and drink out of your little cup, and sleep in your little bed—if you will" +
                "promise me this I will go down below, and bring you your golden ball up again.”\n" + "\n"+
                "   “Oh, yes,” said she, “I promise you all you wish, if you will but bring me my ball back again.” But she thought: “How the silly frog does talk! All he does is" +
                "to sit in the water with the other frogs, and croak! He can be no companion to any human being!”\n" +"\n"+
                "   But the frog when he had received this promise, put his head into the water and sank down, and in a short while came swimming up again with the ball in" +
                "his mouth, and threw it on the grass. The King’s daughter was delighted to see her pretty plaything once more, and picked it up, and ran away with it. " +
                "“Wait, wait,” said the frog. “Take me with you. I can’t run as you can.” But what did it avail him to scream his croak, croak, after her, as loudly as he could? " +
                "She did not listen to it, but ran home and soon forgot the poor frog, who was forced to go back into his well again.\n" +"\n"+
                "   The next day when she had seated herself at table with the King and all the courtiers, and was eating from her little golden plate, something came creeping" +
                "splish splash, splish splash, up the marble staircase, and when it had got to the top, it knocked at the door and cried: “Princess, youngest princess, open the door for me." +
                "” She ran to see who was outside, but when she opened the door, there sat the frog in front of it. Then she slammed the door to, in great haste, sat down to dinner again, and was quite frightened. " +
                "The King saw plainly that her heart was beating violently, and said: “My child, what are you so afraid of? Is there perchance a giant outside who wants to carry you away?” " +
                "“Ah, no,” replied she,“it is no giant, but a disgusting frog.”\n" + "\n"+
                "   “What does the frog want with you?” “Ah, dear father, yesterday as I was in the forest sitting by the well, playing, my golden ball fell into the water. " +
                "And because I cried so, the frog brought it out again for me; and because he so insisted, I promised him he should be my companion, but I never thought he would be able to come out of his water! " +
                "And now he is outside there, and wants to come in to me.”\n" +
                "   In the meantime it knocked a second time, and cried:\n" +
                "   “Princess! youngest princess!Open the door for me!\n" +
                "   Do you not know what you said to me\n" +
                "   Yesterday by the cool waters of the well?\n" +
                "   Princess, youngest princess!\n" +
                "   Open the door for me!”\n" + "\n" +
                "   Then said the King: “That which you have promised must you perform. Go and let him in.” She went and opened the door, and the frog hopped in and followed her, step by step, to her chair. " +
                "There he sat and cried: “Lift me up beside you.” She delayed, until at last the King commanded her to do it. Once the frog was on the chair he wanted to be on the table, and when he was on the table he said: “Now, push your little golden plate nearer to me that we may eat together.” " +
                "She did this, but it was easy to see that she did not do it willingly. The frog enjoyed what he ate, but almost every mouthful she took choked her. " +
                "At length he said: “I have eaten and am satisfied; now I am tired, carry me into your little room and make your little silken bed ready, and we will both lie down and go to sleep.”\n" + "\n"+
                "   The King’s daughter began to cry, for she was afraid of the cold frog which she did not like to touch, and which was now to sleep in her pretty, clean little bed. " +
                "But the King grew angry and said: “He who helped you when you were in trouble ought not afterwards to be despised by you.” So she took hold of the frog with two fingers, carried him upstairs, and put him in a corner. " +
                "But when she was in bed he crept to her and said: “I am tired, I want to sleep as well as you, lift me up or I will tell your father.” " +
                "At this she was terribly angry, and took him up and threw him with all her might against the wall. “Now, will you be quiet, odious frog,” said she. " +
                "But when he fell down he was no frog but a king’s son with kind and beautiful eyes. He by her father’s will was now her dear companion and husband. " +
                "Then he told her how he had been bewitched by a wicked witch, and how no one could have delivered him from the well but herself, and that tomorrow they would go together into his kingdom. Then they" +
                "went to sleep, and next morning when the sun awoke them, a carriage came driving up with eight white horses, which had white ostrich feathers on their heads, and were harnessed with golden chains, and behind stood the young" +
                "King’s servant, faithful Henry. Faithful Henry had been so unhappy when his master was changed into a frog, that he had caused three iron bands to be laid round his heart, lest it should burst with grief and sadness. The carriage was to" +
                "conduct the young King into his kingdom. Faithful Henry helped them both in, and placed himself behind again, and was full of joy because of this deliverance." +
                "And when they had driven a part of the way, the King’s son heard a cracking behind him as if something had broken. So he turned round and cried: “Henry, the carriage is breaking.”\n" + "\n"+
                "   “No, master, it is not the carriage. It is a band from my heart, which was put there in my great pain when you were a frog and imprisoned in the well.” Again" +
                "and once again while they were on their way something cracked, and each time the King’s son thought the carriage was breaking; but it was only the bands which were springing from the heart of faithful Henry because his master was set free and was happy. \n"
                , R.drawable.frogking, "The Brothers Grimm"));
        stories.add(new Stories("The Little Mermaid",
                        "   Long time ago there lived a sea king in a coral palace that was very deep at the bottom of the sea. He had six daughters. While the five of his daughters were happy, the youngest of them was unhappy.\n" + "\n" +
                                "   The little mermaid love the world above the sea. She often swam to the surface of the sea and looked the beautiful blue sky, sun and the green trees of the distant land. She used to feel sad when the time to get back home, came.\n" +"\n" +
                                "   In the middle of a night, The little mermaid left her home and came to the surface, secretly. She sat on a rock and sang a song. She had very beautiful voice. In the dark and stormy night, the high waves crashed a ship and the ship rolling and pitching on the sea. " + "\n" + "\n" +
                                "   Beside the ship a young man was signalling for help. The little mermaid immediately rescued him. She brought him to the shore and rested him against a rock. She fell in love with this young man, the most handsome she had ever seen. A few minutes later, a young girl came and looked them. The little mermaid immediately left the surface and reached her home.\n" + "\n" +
                                "   The little mermaid always thought of the young man. she met a sea witch and told her that she want to be a human. So that she could walk and dance on the land to meet the prince who she love. The witch agreed to consent the wish on two condition. First, the witch will take the beautiful voice of the little mermaid," + "\n" +
                                " so the little mermaid can’t talk and sing. Second, if the young man marries someone else, the little mermaid will die and become foam of the sea. The little mermaid agreed and was soon transformed into a beautiful girl wearing splendid clothes.\n" + "\n" +
                                "   The little Mermaid reached the young man palace and feeling that the young man would recognize her as the rescuer. Not knowing anything about the girl, the palace guards did not allow her inside. Because she can’t speak anything. Listen to the music coming from the palace, she start to dance beautifully. " + "\n" +
                                "   The young man come suddenly and see a beautiful girl with long hair and beautiful dance. He like her and allow her to join with him in the palace. The young man said that the little mermaid remembered him with someone who saved his life. The young man asked her to dance at his party. The little mermaid dance beautifully and charm everyone.\n" + "\n" +
                                "   Day after day, they are to be close. The prince who is the young man said that He fell in love with a beautiful girl who had beautiful voice who saved his life, but he has never been seeing her until now. He think that He will never meet her anymore, so He’ll marry a beautiful young girl who found him at the edge of the sea. The little mermaid felt very sad to hear that. The little mermaid wanted to tell him that She was the girl. But she can’t spoke.\n" + "\n" +
                                "   The wedding has come. The little mermaid came to the palace and saw the prince with the princess. She ran out of the palace and reached the edge of the sea. Sad about what happened to her, she entered the sea, died and became foam of the sea.\n", R.drawable.png_transparent_little_mermaid_ariel_illustration_mermaid_mermaid_flower_fictional_character_cartoon_removebg_preview,"Hans Christian Andersen"));
        stories.add(new Stories("Beauty and The Beast",
                "   Once upon a time, there lived a handsome prince in a beautifful castle. He was so arrogant, he claimed that he had everything in this world. One day, there was a witch who hated the prince a lot. She used her magic to make the prince became a beast. She said that the prince could return to be handsome if only he could find someone who trully loved him and accepted him whatever he was. Started from that moment, the prince never went out from his castle. Some months later, there was an old man who cameto the yard of  his castle. The old man took a red rose at his yard without permission. The prince was so angry and he said that he wanted to kill the old man. The old man explained that he took the red rose for her daughter named Bella, then the old man promised to the prince that he would like to comeback to the prince after giving that rose to his daughter. The prince then let the old man left the castle but he asked the old man to send her daughter Bella to accompany him in the palace. The old man was so sad to tell everything he faced to her daughter, but her daughter Bella promised to do everything for her father. The Old man was so sad to let her daughter lived with a beast in a very big castle but he couldn’t do anything. Bella then started to live in the castle with the beast. The beast treated her as a maid, but Bella was always so patient. Day by day, the beast fallen in love with Bella. He was so admire with her beauty and her patience.\n" + "\n" +
                        "   One day, Bella got the information that her father was in a serious illness. She said to the beast that she wanted to take care of her father for a while. The beast gave her permission to take care of her father for only one week, then Bella agreed with the requirement from the beast. Unfortunately, after taking care of her father, Bella forgot that she should come back to the castle in one week. Then she directly went to the castle after remembering her promise.\n" +
                        " \n" +
                        "   Bella was so surprised when knowing the beast laid down in the floor without breathing. Bella ran and hugged the beast tightly. She cried loudly and asked the beast to forgive her because she came late. She also said that she loved the beast and she would accept the beast whatever he was. suddenly the miracle happened. Surprisingly, the beast woke up and he became a very handsome prince. Bella was so surprise. The prince told to Bella about who actually he was. Finally they got married and everyone lived happily ever after. \n", R.drawable.belle, "Gabrielle-Suzanne Barbor de Villeneuve"));
        stories.add(new Stories("The Old Sultan",
                "   A farmer once had a faithful dog called Sultan, who had grown old, and lost all his teeth, so that he could no longer bite. One day the farmer was standing with his wife before the house door, and said, “Tomorrow I intend to shoot Old Sultan, he is no longer of any use.”\n" + "\n" +
                        "   His wife, who felt pity for the faithful beast, answered, “He has served us so long, and been so faithful, that we might well keep him.”\n" + "\n" +
                        "   “Eh! What?” Said the man. “You are not very sharp. He has not a tooth left in his mouth, and no thief is afraid of him; now he may be off. If he has served us, he has had good feeding for it.”\n" + "\n" +
                        "   The poor dog, who was lying stretched out in the sun not far off, had heard everything, and was sorry that the morrow was to be his last day. He had a good friend, the wolf, and he crept out in the evening into the forest to him, and complained of the fate that awaited him. “Listen well,” said the wolf, \"and don’t be sad. I will help you out of your trouble. I have thought of something. Tomorrow, early in the morning, your master is going with his wife to make hay, and they will take their little child with them, for no one will be left behind in the house. As usual, during work time, they will lay the child under the hedge in the shade; you lie there too, just as if you wished to guard it. Then I will come out of the wood, and carry off the child. You must rush swiftly after me. I will let it fall, and you will take it back to its parents, who will think that you have saved it, and will be far too grateful to do you any harm - quite the opposite; you will be dear to their hearts, and they will never let you lack for anything again.”\n" + "\n" +
                        "   The plan pleased the dog, and it was carried out just as it was arranged. The father screamed when he saw the wolf running across the field with his child, but when Old Sultan brought it back, then he was full of joy, and stroked him and said, “Not a hair of yours shall be hurt, you shall eat my bread free as long as you live.” To his wife he said, “Go home at once and make Old Sultan some soggy bread that he will not have to bite, and bring the pillow out of my bed, I will give it to him to lie upon.” From that time on, Old Sultan was as well off as he could wish to be.\n" + "\n" +
                        "   Soon afterwards the wolf visited him, and was pleased that everything had succeeded so well. “But, listen well,” said he, “you will just wink an eye when I carry off one of your master’s fat sheep.”\n" + "\n" +
                        "   “Do not reckon upon that,” answered the dog. “I will remain true to my master; I cannot agree to that.” The wolf, who thought that this could not be spoken in earnest, came creeping about in the night and was going to take away the sheep. But faithful old Sultan barked, and the farmer chased after the wolf with a big stick. The wolf had to pack off, but he cried out to the dog, “Wait a bit, you scoundrel, you shall pay for this.”\n" + "\n" +
                        "   The next morning the wolf sent the wild boar to challenge the dog to come out into the forest so that they might settle the affair. Old Sultan could find no one to stand by him but a cat with only three legs, and as they went out together the poor cat limped along, and at the same time stretched out her tail into the air with pain.\n" + "\n" +
                        "   The wolf and his friend were already on the spot appointed, but when they saw their enemy coming they thought that he was bringing a sabre with him, for they mistook the outstretched tail of the cat for one. When the poor beast hopped on its three legs, they could only think every time that it was picking up a stone to throw at them. So they were both afraid; the wild boar crept into the under-wood and the wolf jumped up a tree.\n" +"\n" +
                        "   The dog and the cat, when they came up, wondered that there was no one to be seen. The wild boar, however, had not been able to hide himself altogether; and one of his ears was still to be seen. Whilst the cat was looking carefully about, the boar moved his ear. The cat, who thought it was a mouse moving there, jumped upon it and bit it hard. The boar made a fearful noise and ran away, crying out, “The guilty one is up in the tree!” The dog and cat looked up and saw the wolf, who was ashamed of having proved himself to be so afraid, and made friends with the dog.\n",
                R.drawable.oldsultan, "Brothers Grimm"));
        stories.add(new Stories("Sleeping Beauty",
                "   Once upon a time, there is a golden castle with a happy king and queen. They are full of love and the people love them too. Yet, they still have no child to complete their happiness.\n" + "\n" +
                        "   After many months and years, the queen finally gives birth to a baby girl. The kingdom is very happy with their new princess. The king and queen make a big party and invite everybody in the kingdom, especially the forest fairies. They bless the child with many gifts such as kindness, beauty, richness. and many more. However, the king and queen forget to invite one fairy that comes and give a curse to the child. “When the princess is fifteen years old she will die impaled by sewing needles.\n" + "\n" +
                        "   Everyone terrified with the wicked fairy curse. Fortunately, there is one fairy left that haven’t given and blessing. The king and queen beg her to undo the curse. Unfortunately, she can not do anything to break the spell. She can only add something. “your daughter will not die because of the needle, but she will sleep for hundreds of years and can only be woken up with a true love kiss”.\n" + "\n" +
                        "   The princess grows up to be a lovely child and sweet. The kingdom tries to prevent the curse by destroying all sewing objects. Until she turns fifteen, the princess has never seen a sewing machine. That is why the wicked fairy pretends to be an old lady that makes cloth with an old sewing machine with a needle. The princess has never seen such a thing. The wicked fairy let the princess touch the machine and pricked her finger to the needle. The princess falls to the ground and the wicked fairy left the kingdom thinking the princess is dead just like her curse.\n" + "\n" +
                        "   As foreseen, all the other fairies put the sleeping princess to her bedroom. So, she is not lonely, they put everyone in the kingdom to sleep too. They cover the kingdom with torn and thick threes and shield the kingdom for many years.\n" + "\n" +
                        "   Hundred years later, stories spread from families to royals of sleeping beauty and a kingdom covered with prickly wild trees. A prince cautious about the tale and seek if it is true. He goes to the forest to the forest for the hidden kingdom. When the prince came to the palace, he saw everyone fall asleep. He explores the palace until he reaches sleeping beauty’s bedroom. Then he looks at the beautiful princess and kissed her. it broke the curse, sleeping beauty woke up and so does everyone in the kingdom.\n", R.drawable.sleepingbeauty, "Charless Perrault"));
        stories.add(new Stories("The Princess and The Pea",
                "   There was once a Prince who wished to marry a Princess; but then she must be a real Princess. " +
                        "   He travelled all over the world in hopes of finding such a lady; but there was always something wrong. " +
                        "   Princesses he found in plenty; but whether they were real Princesses it was impossible for him to decide, for now one thing, now another, se¬emed to him not quite right about the ladies. " +
                        "   At last he returned to his palace quite cast down, because he wished so much to have a real Princess for his wife.\n " + "\n"+
                        "   One evening a fearful tempest arose, it thundered and lightened, and the rain poured down from the sky in torrents: besides, it was as dark as pitch. " +
                        "   All at once there was heard a violent knocking at the door, and the old King, the Prince’s father, went out himself to open it. It was a Princess who was standing outside the door. \n" + "\n"+
                        "   What with the rain and the wind, she was in a sad condition; the water trickled down from her hair, and her clothes clung to her body. She said she was a real Princess. " +
                        "   ‘Ah! we shall soon see that!’ thought the old Queenmother; however, she said not a word of what she was going to do; but went quietly into the bedroom, took all the bed-clothes off the bed, and put three little peas on the bedstead. " +
                        "   She then laid twenty mattresses one upon another over the three peas, and put twenty feather beds over the mattresses. \n" +"\n"+
                        "   Upon this bed the Princess was to pass the night. The next morning she was asked how she had slept. ‘Oh, very badly indeed!’ she replied. ‘I have scarcely closed my eyes the whole night through. " +
                        "   I do not know what was in my bed, but I had something hard under me, and am all over black and blue. It has hurt me so much!’ Now it was plain that the lady must be a real Princess, since she had been able to feel the three little peas through the twenty mattresses and twenty feather beds. \n" +"\n"+
                        "   None but a real Princess could have had such a delicate sense of feeling. The Prince accordingly made her his wife; being now convinced that he had found a real Princess. " +
                        "   The three peas were however put into the cabinet of curiosities, where they are still to be seen, provided they are not lost. Wasn’t this a lady of real delicacy? \n", R.drawable.princessandthepea, "Hans Christian Andersen"));
        stories.add(new Stories("The Little Red Riding Hood",
                "   Once upon a time there lived a little country girl, the prettiest creature who was ever seen. Her mother had a little red riding hood made for her. Everybody called her Little Red Riding Hood.\n" +
                        "   One day her mother said to her: “Go my dear, and see how your grandmother is doing, for I hear she has been very ill.”\n Little Red Riding Hood set out immediately.\n" +
                        "   As she was going through the wood, she met with a wolf. He asked her where she was going.\n" + "\n"+
                        "   “I am going to see my grandmother.”\n" +
                        "   “Does she live far off?” said the wolf.\n" +
                        "   “It is beyond that mill you see there”.\n" +
                        "   It was not long before the wolf arrived at the old woman’s house. He knocked at the door.\n" +
                        "   Tap, tap, tap.\n  “Who’s there?”\n" +
                        "    “Your grandchild, Little Red Riding Hood,” replied the wolf, faking her voice.\n" +
                        "   The good grandmother called out, “Pull the string, and the latch will go up.”\n" +
                        "   The wolf pulled the string and the door opened, and then he immediately fell upon the good woman and ate her up in a moment.\n He then shut the door and got into the grandmother’s bed, expecting Little Red Riding Hood, who came some time afterwards and knocked at the door.\n" +
                        "   Tap, tap, tap.\n “Who’s there?”\n" +
                        "   “It is your grandchild, Little Red Riding Hood.”\n" +
                        "   The wolf cried out, “Pull the string, and the latch will go up.”\n Little Red Riding Hood pulled the string, and the door opened.\n  \n" +
                        "   “Grandmother, what big arms you have!”\n" +
                        "   “All the better to hug you with, my dear.”\n" +
                        "   “Grandmother, what big ears you have!”\n" +
                        "   “All the better to hear you with, my child.”\n" +
                        "   “Grandmother, what big eyes you have!”\n" +
                        "   “All the better to see you with, my child.”\n" +
                        "   “Grandmother, what big teeth you have got!”\n" +
                        "   “All the better to eat you up with.”\n Fortunately, a hunter was passing near by the hut. He heard the wolf, and recognised him right away. He ran over to the window. He took a good aim, and that was the end of the wolf.\n", R.drawable.pngtree_little_red_riding_hood_with_basket_clip_art_png_image_5978948_removebg_preview__1_, "Charles Perrault"));
        stories.add(new Stories("Hansel and Gretel",
                "   There once lived a poor woodcutter and his wife who had two children named Hansel and Gretel. The woodcutter’s wife was evil. Because they could not take care of their children, his wife asked him to leave their children in the middle of the forest.\n" + "\n" +
                        "   Hansel and Gretel knew about their parents’ plan, so they came up with a plan of dropping pebbles along the way their father took them. All they had to do then was to follow the line of the pebbles back home. Their parents were surprised to see them back and decided to take them again with a different route the next day.\n" + "\n" +
                        "   This time, Hansel and Gretel could not find any pebbles. Luckily, Hansel had some breadcrumbs in his pocket and dropped them along the way. Alas! The birds ate up all the crumbs and now they were completely lost.\n" + "\n" +
                        "   They kept walking and went deeper into the forest. After walking for hours, they saw a hut that was made out of chocolate, cookies, and candies. “Look, Hansel! It’s a chocolate door!” shouted Gretel in delight. Then they both hungrily ate it.\n" + "\n" +
                        "   Suddenly, a wicked witch who owned the hut came and caught them. She locked up Hansel in a cage and planned to make a soup out of him. Then she asked Gretel to help her to heat a large pot of water for the water. But just as the witch bent to check the water’s temperature, Gretel pushed her from behind and the witch fell into the boiling water. She howled in pain and died instantly. Gretel immediately freed Hansel and they both filled their pockets with the witch’s jewels.\n" + "\n" +
                        "   At last, Hansel and Gretel managed to find their way back home and gave the jewels to their parents. Their parents were so sorry and welcomed them back with tears of joy. The family was never poor and hungry again.\n",
                R.drawable.hansel_and_gretel_580x386_removebg_preview, "Brothers Grimm"));
        stories.add(new Stories("The Tree Little Pigs",
                "   A long time ago, there lived three little pigs that wanted to build their own house. The first little pig built his house with dried straw and the second little pig built his house with sticks. They both finished their houses in a short time because they were too lazy to build a proper house. Then they both sang and danced all day. Meanwhile, the third little pig was building his house with bricks and he worked hard all day.\n" + "\n" +
                        "   One day, a big bad wolf watched the two little pigs were dancing and singing outside. “What a juicy tender meal they will make!” said the wolf to himself. Then the wolf chased both pigs but they both run away and hid in their own houses. The wolf went to the first little pig’s house that was made out of dried straw. He took a deep breath and blew the house down in minutes.\n" + "\n" +
                        "   The frightened little pig ran to the second pig’s house that was made of sticks. The wolf followed and now he came to the second little pig’s house. He took a deep breath and blew the house down in minutes. Now, the two little pigs were terrified and ran away to the third little pig’s house.\n" + "\n" +
                        "   The wolf then followed them and came to the third house that was made of bricks. He took a deep breath and blew the house but nothing happened. He kept trying to blow the house for hours but the house was too strong. Then he looked up at the roof. He climbed up and tried to enter through the chimney.\n" +"\n" +
                        "   The three little pigs inside heard a noise from the chimney. They know it was the wolf, so they boiled a huge pot of water and kept it below the chimney. The wolf fell into it and died. The first two little pigs now felt so sorry for being so lazy and promised to build a house with bricks.\n"
                ,R.drawable.__little_pigs_png_photos_removebg_preview_removebg_preview__1_,"James Halliwell-Philips"));
        stories.add(new Stories("The Oak Tree and The Reeds",
                "   Once Upon a time, there flowed a river near a village. An old Oak tree stands on the bank of that river. The Oak tree always kept thinking that he was very strong and mighty. The Oak tree was very tall and could see at a far distance. He thought that the wind could not harm him as he was too intense. The stem of the old tree was very strong and would not bend or break with the intense wind; the old tree used to think.\n" + "\n" +
                        "   There were many bushes of Reeds under the shade of the big old Oak tree. These Reeds seemed like long grass from a far distance. One day the Oak tree said to the Reeds,\n" + "\n" +
                        "   “O Reeds! You are so weak and light weighted! You can bend even with a small blow of air. I am sure that the intense wind can break you on blowing while I will remain standing even then.”\n" + "\n" +
                        "   One day, the wind started blowing intensely.\n" +  "\n" +
                        "   The old and strong Oak tree remained standing on its place with pride and said to the Reeds,\n" + "\n" +
                        "   “Did you see, even the intense wind could not harm or bend me! Look at the way you are bending?”\n" +"\n" +
                        "   The Reeds did not say anything to the Oak tree. As the Reeds were listening to the Oak tree, the wind became furious. The wind started blowing even more intensely. The old Oak tree encountered the wind for some time but withdrew at last.\n" + "\n" +
                        "   The branches of the tree started breaking, and then in no time, its stem broke down into two pieces from the middle. On the other hand, the Reeds remained on the ground while the wind blew furiously. But they stood up again as the wind stopped blowing and said to see the old Oak’s tree,\n" + "\n" +
                        "   “They who strut with pride do break and who bend humbly remain safe.”\n", R.drawable.kisspng_tree_free_content_clip_art_cartton_tree_5aa8e95c698dc7_6555744815210192284324_removebg_preview, "Aesop"));
        stories.add(new Stories("The Ugly Duckling",
                "   One upon time, a mother duck sat on her eggs. She felt tired of sitting on them. She just wished the eggs would break out.\n" +
                        " However the largest egg had not cracked. The mother duck sat on it for several days. Finally, it cracked and a huge ugly duckling waddled out. The mother duck looked at him in surprise. He was so big and very gray. He didn't look like the others at all. He was like a turkey\n" + "\n" +
                        " When the mother duck brought the children to the pond for their first swimming lesson. The huge grey duckling splashed and paddled about just as nicely as the other ducklings did. \"That is not a turkey chick. He is my very own son and quite handsome\" the mother said proudly\n" + "\n" +
                        "   However, the other animals didn't agree. They hissed and made fun of him day by day. Even his own sisters and brothers were very unkind. \"You are very ugly\" they quacked.\n" + "\n" +
                        " The little poor duckling was very unhappy. \"I wish I looked like them\" he thought to himself. One day, the ugly duckling run away and hid in the bushes. The sad duckling lived alone through the cold and snow winter. Finally the spring flowers began to bloom. While he was swimming in the pond, he saw three large white swans swimming toward him. \"Oh, dear. these beautiful birds will laugh and peck me too\" he said to himself. But the swans did not attack him. Instead, they swam around him and stroked him with their bills. As the ugly duckling bent his neck to speak to them, he saw his reflection in the water. He could not believe his eyes. \"I am not an ugly duckling but a beautiful swam\" he exclaimed.\n" + "\n" +
                        " He was very happy. From that day on, he swam and played with his new friends and was happier than he had never been.\n", R.drawable.ugly, "Hans Christian Andersen"));
        stories.add(new Stories("Pinocchio",
                "   In the past, there was a puppeteer whose name is Geppetto. He eager to have a son very much but his wife passed away several years ago. One day, he got an idea to make a puppet in order not to be lonely again. He made a puppet all day long. Finally, in the morning he had finished his work and he named the puppet Pinocchio. Soon he felt lonely again since Pinocchio couldn’t walk or talk by itself. One night, Geppetto prayed to the God to become a real boy. He always thought it on his mind in his dream.\n" + "\n" +
                        "   In the next morning, he was surprised that Pinocchio was alive. He taught Pinocchio how to walk, how to read, how to speak and to do other things as human. He then studied at an elementary school. One day, Pinocchio felt bored and it made him go home late. When Pinocchio finally came home, Geppetto asked him. He said that he was on school but he wasn’t. Instantly, Pinocchio’s nose grew longer and longer and it meant that Pinocchio has lied.\n" + "\n" +
                        "   The next morning, Pinocchio was kidnaped by the owner of circus. Pinocchio soon became a slave for the circus. He was so famous because he was a puppet which can talk. Geppetto worried about him because Pinocchio had not been going home for almost two days. He tried to find Pinocchio everywhere but he found nothing. When he searched him on the sea, big wave smashed him. He was then in whale’s stomach when he awoke. He couldn’t find the way to go out.\n" + "\n" +
                        "   In the other side, Pinocchio finally could escape out from the circus. He came home but nobody was there. Latter on, he searched Geppetto in the sea. He got the same accident like Geppetto and he met Geppetto in whale’s stomach. Both of them got out from its stomach by making a fire. In the end of the story, they went home together and lived happily ever after.\n",
                R.drawable.istockphoto_1195925453_612x612_removebg_preview, "Carlo Collodi"));
        stories.add(new Stories("The Snow Queen",
                "   Once, there was a boy called Kay and a girl called Gerda, who were best friends. They were as close as brother and sister, and they lived next door to each other. Roses grew in the window boxes of their two houses and entwined together. In the summer, the children could sit on their balconies and talk to each other. In the winter, they played in each other's houses.\n" + "\n" +
                        "   One winter, when Kay was visiting Gerda and her grandmother, the children were reading their favorite book by the fireplace. Suddenly, Kay called out in pain. \"My heart,\" he cried, \"and my eye!\"\n" + "\n" +
                        "   Two splinters of glass from an evil magician's mirror had pierced Kay's heart and eye. Now his heart was as cold as ice. From that moment on, he didn't want to play with Gerda any more.\n" + "\n" +
                        "   One day, when Kay was playing on the ice, he tied his sled to that of a mysterious stranger.\n It turned out to be the Snow Queen, and she wouldn't let Kay go. She carried him away to her palace.\n" + "\n" +
                        "   Gerda couldn't understand what had happened to Kay and searched for him everywhere. In the end she left their village, determined to find him.\n" + "\n" +
                        "   After weeks of searching, she met a talking reindeer, who promised to take her to the Palace of Ice, where the Snow Queen was keeping Kay a prisoner\n" + "\n" +
                        "   Gerda had never been so cold in her life. The palace was made of ice. She ran through halls of icicles and corridors of packed snow, until she came to a vast room with a frozen lake in the middle.\n" + "\n" +
                        "   And on the lake sat her old playmate. \"Kay!\" cried Gerda, but he did not know her. Gerda ran across the lake, slipping and sliding. \"It's me, Gerda,\" she said. But still he did not recognize her. Gerda could not bear it.\n", R.drawable.snowqueen, "Hans Christian Andersen"));
        stories.add(new Stories("Thumbelina",
                "   Once upon a time, there was a kind woman who had no children, longed for a baby and would often say, “How I would love to have a baby girl, even a tiny little one.” A beautiful fairy heard her wish one day, and gave her a little seed to plant in a flowerpot. When the seed bloomed into a tulip, the woman saw a tiny, beautiful girl inside, no bigger than her thumb. She decided to call her Thumbelina. She was so small that she had a walnut shell for a bed and used petals as a blanket. Then, an ugly toad fell in love with Thumbelina. One night when she was sleeping, he carried her off to his lily pad in a pond. Thumbelina was very unhappy. A swallow was passing by and saw how sad she looked, and said, “Come south with me to warmer lands.” Young Thumbelina flew away on the swallow’s back. They flew across the seas and came to a land of sunshine. The swallow said, ” This is my home. You can live in one of the loveliest and biggest flowers.” When Thumbelina stepped inside, she found a handsome fairy, as tiny as her, in its heart. He was the son of the king of flowers and he fell in love with Thumbelina. He asked her to marry him. So Thumbelina became queen of the flowers and the two lived happily ever after.\n \n",
                R.drawable.pngtree_cartoon_thumbelina_png_image_4406364_removebg_preview, "Hans Christian Andersen"));
        return stories;
    }
}
